### ISSUE TITLE
Adding an example for storing Audio received throu JDA as WAV file.

### ISSUE THREAD

**Issue by DxsSucuk** [DV8FromTheWorld/JDA-Website#34]
I would like to request an example for users of how they could store audio files from voicechannels.

I already worked on this feature thanks to @DV8FromTheWorld I got it working. [Here](https://github.com/Ree6-Applications/Ree6/blob/feature/voice-recording/src/main/java/de/presti/ree6/audio/AudioPlayerReceiveHandler.java) would be an example of a working prototype.

**Comment by MinnDevelopment** [comment]
Audio receive will not be documented here, as it is a generally unstable and unreliable feature. Discord also does [not officially support audio receive](https://github.com/DV8FromTheWorld/JDA/issues/904).
