### ISSUE TITLE
Wiki entry for Interactions does not include SelectionMenu information

### ISSUE THREAD

**Issue by Hok-2323** [DV8FromTheWorld/JDA-Website#4]
## General Troubleshooting

- [x] I have checked for similar issues.
- [x] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

Interaction wiki isn't update to date 

### Expected Behavior

SelectionMenu already came out

### Code Example or Reproduction Steps

N/A

### Code for JDABuilder or DefaultShardManagerBuilder Used

N/A

### Exception or Error

N/A

**Comment by DV8FromTheWorld** [comment]
This should be handled by #3
